---
title: "Homework 3"
author: "Md Muhtasim Billah, Jugal Marfatia, Namrata Ray"
date: "10/24/2019"
output: pdf_document
---
\section{Question 1}
# Pooled t-test
```{r warnings=FALSE}
#define the vectors
rationA=c(10,8,12,11,9,6,6,9,5,6)
rationB=c(13,15,14,13,17,9,10,8,10,8)
#calculate the params
n1=length(rationA)
n2=length(rationB)
xbar1=mean(rationA)
xbar2=mean(rationB)
s1=sd(rationA)
s2=sd(rationB)
#observed statistic
obs=xbar1-xbar2
obs
#the pooled estimate of standard deviation
s.p=sqrt(((n1-1)*s1^2+(n2-1)*s2^2)/(n1+n2-2))
s.p
#the t statistic
t.stat=(xbar1-xbar2)/(s.p*sqrt(1/n1+1/n2))
t.stat
#degrees of freedom
df=n1+n2-2
df
#the p-value
p=pt(t.stat,df)
p
#using the built-in package
t.test(rationA,rationB,alternative="less",var.equal=TRUE)
```

## Welch's t test
```{r warnings=FALSE}
#define the vectors
rationA=c(10,8,12,11,9,6,6,9,5,6)
rationB=c(13,15,14,13,17,9,10,8,10,8)
#calculate the params
n1=length(rationA)
n2=length(rationB)
xbar1=mean(rationA)
xbar2=mean(rationB)
var1=var(rationA)
var2=var(rationB)
#the t statistic
t.prime=(xbar1-xbar2)/sqrt((var1/n1)+(var2/n2))
t.prime
#degrees of freedom
c=(var1/n1)/((var1/n1)+(var2/n2))
df=((n1-1)*(n2-1))/((n2-1)*(c^2)+(1-c^2)*(n1-1))
df
#the p-value
p=pt(t.prime,df)
p

#using the built in package
t.test(rationA,rationB,alternative="less")
```
# Wilcoxon rank sum
```{r}
a= c(10,6,8,6,12,9,11,5,9,6)
b= c(13,9,15,10,14,8,13,10,17,8)
wilcox.test(b,a, correct=FALSE)
```
# Bootstrap
```{r}

x1= c(10,6,8,6,12,9,11,5,9,6)
x2= c(13,9,15,10,14,8,13,10,17,8)

a1=mean(x1)
a2=mean(x2)
n1=length(x1)
n2=length(x2)

#observed t statistic
t0=abs( a1-a2)/sqrt((var(x1)/n1)+(var(x2)/n2))

# initialize a vector
storet=0
x=cbind(x1,x2)
# a loop for the 1000 bootstrap samples
for (i in 1:1000)
{
  x1b=sample(x,size=n1,replace=T)
  x2b=sample(x,size=n2,replace=T)
  tb=(mean(x1b)-mean(x2b)-a1+a2)/sqrt((var(x1b)/n1)+(var(x2b)/n1))
  storet[i]=tb
}
hist(storet)
tq=quantile(storet,prob=seq(0,1,.025))
tq[2]
tq[40]
t0
p.value=(sum(storet>t0))/1000
p.value
```
\section{Question 2}
# Bonferroni method
```{r}
g= c(0.1352, 0.4054, 0.9605, 0.3055, 0.9413, 0.0001, 0.2873, 0.0063, 0.0015, 0.4540, 0.2662, 0.9216, 0.0085, 0.4854, 0.1328, 0.6122, 0.7550, 0.0850, 0.0005, 0.9365, 0.0010, 0.9199, 0.1957, 0.0003, 0.7026, 0.6983, 0.1643, 0.0045, 0.4640, 0.0007, 0.0159, 0.9722, 0.0305, 0.0117, 0.4884, 0.1047, 0.9351, 0.4492, 0.0005, 0.2230, 0.2680, 0.4378, 0.7118, 0.0090, 0.2719, 0.0049, 0.9583, 0.6275, 0.3892, 0.9458, 0.6927, 0.7129, 0.5807, 0.5474, 0.0004, 0.2277, 0.4881, 0.7835, 0.0009, 0.1750, 0.9480, 0.0799, 0.0432, 0.7160, 0.3428, 0.7579, 0.3393, 0.6708, 0.0007, 0.0002, 0.7694,0.7038,0.5689,0.0154,0.0332,0.7097,0.2861,0.0046,0.1357,0.7214,0.7761,0.7419,0.0277,0.4675,0.0219,0.3974,0.9451,0.7148,0.9055,0.0003,0.7223,0.7438,0.3308,0.0059,0.1340,0.4247,0.2700,0.5124, 0.6322, 0.0160)

reject = c(rep(0.05/100, 100))

print(g[g<reject])
print("Number of genes that Reject the null: ")
print(length(g[g<reject]))
```
# FDR method
```{r}
g_sort= sort(g, decreasing = FALSE)

reject = c(rep(0.05/100, 100) * seq(1, 100,1))

print(g_sort[g_sort<reject])
print("Number of genes that Reject the null: ")
print(length(g_sort[g_sort<reject]))
```
# Bonferroni-Holm method
```{r}
g_sort= sort(g, decreasing = FALSE)

reject = c(rep(0.05, 100) / (100 - seq(1, 100, 1) + 1) )

print(g_sort[g_sort<reject])
print("Number of genes that Reject the null: ")
print(length(g_sort[g_sort<reject]))
```

# Step up method
```{r}
g_sort= sort(g, decreasing = TRUE)

reject = c(rep(0.05, 100) / (100 - seq(1, 100, 1) + 1) )

print(g_sort[g_sort<reject])
print("Number of genes that Reject the null: ")
print(length(g_sort[g_sort<reject]))
```